export const ICON_SIZE = 24

export const MAIN_CONTENT_MARGIN_LEFT_RIGHT_1000PX_OVER = '8rem'
export const MAIN_CONTENT_MARGIN_LEFT_RIGHT_1000PX_UNDER = '2rem'
export const MODAL_CONTENT_PADDING_LEFT_RIGHT = '15rem'
